### ISSUE TITLE
Can't save configuration

### ISSUE THREAD

**Issue by danieladov** [crobibero/jellyfin-plugin-discord#2]
Every time I press "save" Discord Webhook Url and Server Url fields are wiped out and the page reloads without saving anything.

Also when pressing " Send test notification" this error occurs "Uncaught (in promise) TypeError: Cannot read property 'UserId' of undefined at configurationpage?name=DiscordJS&v=10:1502"

**Comment by crobibero** [comment]
There's a bug with jellyfin-web where clicking save the first time refreshes the page. Just reenter the details and hit save; then you should be able to test

**Comment by danieladov** [comment]
I've done it 3 times but it's still reloading

**Comment by crobibero** [comment]
I just tested with my instance and was able to save successfully 

Steps I took to save:
1. Load plugin config
2. Save
3. Let page automatically reload
4. Save again without refreshing

**Comment by danieladov** [comment]
As shown here, it's not working for me. I also tried another browser without any luck
![cantSave](https://user-images.githubusercontent.com/29411250/92675917-cce0a980-f320-11ea-8036-511fa6e6024d.gif)

**Comment by danieladov** [comment]
Close it by accident sorry

**Comment by crobibero** [comment]
Just built `1.2020.910.255`. Can you update the plugin and try now?

**Comment by danieladov** [comment]
It worked! Thank you so much

**Comment by crobibero** [comment]
perfect!

For future reference -> `e.preventDefault;` -> `e.preventDefault();`
