### ISSUE TITLE
[Feature request, idea] Change the tilte of embed message

### ISSUE THREAD

**Issue by aubertlucas** [crobibero/jellyfin-plugin-discord#4]
Currently when a notification is received, it mentions the name of the episode as well as the episode number. The problem is that some episode is called for example "Episode 9". 
So the final result is: [...] S01E09 Episode 9 has been added to ...
As you can see, this is not the most aesthetic way to present something.

It would be nice to have the possibility to change (or even add) the title of the series in the notification for having a result like this :  [...] S01E09 NameOfTvShow has been added to ...
Or  [...] S01E09 NameOfTvShow Episode 9 has been added to ...

**Comment by crobibero** [comment]
I've created a new plugin that allows full customization for the message.
https://github.com/crobibero/jellyfin-plugin-webhook
